### ISSUE TITLE
1.7 Skin renders very strange with some other mods installed

### ISSUE THREAD

**Issue by Lodugh** [ganymedes01/Et-Futurum#70] opened 2016-01-13 14:48 UTC
I made a Modpack with Et Futurum 1.5.4 in it and my skin, that is not yet updated to the 1.8 format, renders very strange. My legs have no skin and the other parts are kinda random in different positions. I have Fastcraft, Optifine, BetterFps, Headcrumbs and a bunch of other mods installed, where I dont think they would make problems with Et Futurum but if you need a full list I will make one.
![2016-01-13_15 29 32](https://cloud.githubusercontent.com/assets/13154183/12297314/e227dfae-ba0c-11e5-8608-0b9295111623.png)
![2016-01-13_15 29 45](https://cloud.githubusercontent.com/assets/13154183/12297315/e255b910-ba0c-11e5-997e-927814fd5b78.png)

**Comment by EzerArch** [comment] 2016-01-13 22:59
Same (solved) problem as mine? https://github.com/ganymedes01/Et-Futurum/issues/54#issuecomment-161842731

**Comment by Lodugh** [comment] 2016-01-14 12:30
Looks like that. Thank you. Should have looked in solved issues.

**Comment by Lodugh** [comment] 2016-01-14 12:33
Well but for me 1.5.4 does not solve the issue, thats strange.

**Comment by buttilda** [comment] 2016-01-14 13:20
I'm not sure what's causing it... definitely some mod you have that conflicts with the feature.
Either remove mod by mod until you find the culprit or just disable the feature (`"Skin Overlays" = false` on the configs), since you said that you haven't updated your skin yet, I recommend that you just do the latter :)

**Comment by buttilda** [comment] 2016-01-14 13:21
Leaving it open so other people can see it and maybe someone will find out which mods are conflicting and can post it here :)

**Comment by Lodugh** [comment] 2016-01-14 13:59
Yes, disabling it solved the problem for now. Thx for the answer :). 
Another thing I noticed is, that sometimes the skin just does not load and I am Steve(regardless whether Skin Overlays are on or off). Although going out of the world and back in makes it load again. But that might just be Minecraft. And sometimes(if Skin Overlays are on) the skin even renders normally but the next time I load a world it does not. Very strange behaviours..
Really cant imagine which mod it could be but I might test around a bit more.

**Comment by buttilda** [comment] 2016-01-14 14:50
I highly doubt Et Futurum would be messing with the skin downloading even with that option turned off, it could be another mod, your internet, or the mojang servers acting up.
I'll have a look regardless, maybe some part of the code is still running even with the config off.

**Comment by bmario** [comment] 2016-01-14 15:48
I have the same issue. After testing a bit around, I found that DragonAPI (the base for Reikas mods) and Galacticraft causing these issues for me. Even if I only load one particular mod together with Et Futurum. However, turning overlay skins off, fixes the glitches for me.

**Comment by Lodugh** [comment] 2016-01-15 19:04
I used none of those, there must be another mod that is causing it..

**Comment by OracleofWuffing** [comment] 2016-03-30 02:44
[Armourer's Workshop](https://github.com/RiskyKen/Armourers-Workshop) from @RiskyKen appears to be such a conflicting mod, I recently upgraded from Et Futurum 1.5.2 to 1.5.5 and started getting [This Console Spam](http://pastebin.com/ASYj2wgj) any time an Armourer block was trying to render a body part.  My steps to reproduce were to make a new flatland world, place an Armourer, quit minecraft, relaunch, join the world again, and then the console would get flooded.

This issue didn't happen in an environment with only Et Futurum 1.5.2 and Armourer's Workshop, but it also doesn't happen if I just do what's already suggested and disable Overlays, so it's "fixed for me," but I figure having someone say what they saw might help anyone else having some trouble with it.

It didn't really result in skins being garbled, though, so I'm sorry if this is just a different but similar issue.

**Comment by esotericist** [comment] 2016-04-15 01:08
Able to reproduce this problem with et futurum 1.5.5 and fossils and archaeology 7.2.1 as a minimal test case.

Out of curiosity, I stepped back et futurum versions until the problem went away. I can say for certain that the garbled skin problem I'm experiencing (nearly identical to initial submitter of this issue) does not occur with 1.5.2, but does occur with 1.5.3 and later, implying the changes in 1.5.3 are related.

Notably, with both 1.5.2 and fossils and archaeology, while the skin isn't garbled the overlay is not present (my server populace has 1.8 skins). My current working theory is F&A does some shenanigans with replacing player model rendering to allow for the rideable dinosaurs. Given the latency involved in that mod's development, I expect whatever's happening there to not be resolved except, well, by eventually moving to 1.8+. For now, disabling the overlays is our server's only viable solution for 1.5.5.

Thought you guys would appreciate the additional data.

**Comment by ghost** [comment] 2017-07-17 16:29
I'm having this issue with Blocksmith Hybrid res pack on.  And disabling skin overlays does not fix it.

**Comment by Creeper01** [comment] 2018-03-20 01:58
I'm having this issue too...I'm still quite new to mods, so how do you disable the skin overlay option?

**Comment by EzerArch** [comment] 2018-03-20 03:16
@Creeper01, read my comment: https://github.com/ganymedes01/Et-Futurum/issues/70#issuecomment-171464831

**Comment by ghost** [comment] 2018-03-20 03:45
@Creeper01  turn skin overlays to false. 

Open the `etfuturum.cfg` file from /config folder and turn this to false just like i have it:
`B:"Skin overlays"=false`

This will disable 1.8 Alex skin but will make your character look normal again.  That feature is buggy and seems to always default to a steve skin with every restart. Probably due to optifine?

You will probably have to restart the game. 

If the skin did not reset also type then restart
`/setPlayerModel steve`  

You may have to open LAN and enable cheats if you're in a Survival world

If you want an Alex skin simply choose a Steve skin that looks like Alex from Minecraft/Mojang account.

**Closed as completed** 2019-05-20 13:28 UTC
