### ISSUE TITLE
Bookshelves the only enchantment table augumentor

### ISSUE THREAD

**Issue by yrsegal** [ganymedes01/Et-Futurum#38] opened 2015-10-04 04:16 UTC
things like Mana Pylons don't increase the max enchantment level.

**Comment by buttilda** [comment] 2015-10-04 06:41
I don't get what you're trying to say here. Could you elaborate?

**Comment by yrsegal** [comment] 2015-10-04 11:17
Normally, a Mana Pylon will increase the maximum enchanting level of an enchanting table by 15, when placed near it. (Bookshelves increase it by 2.) So, you need 15 bookshelves to achieve level 30, and 2 Mana Pylons to achieve level 30.

 With Et Futurum, only bookshelves work.

**Comment by buttilda** [comment] 2015-10-04 14:01
OH I see. Hm I'll see what's going on

**Comment by buttilda** [comment] 2015-10-04 14:03
Looked at the code and it should be working with any mod added blocks.
Very strange. I'll have to do some further testing later and get back to you :)

**Comment by buttilda** [comment] 2015-10-06 15:38
Tried it and it worked...
Placed two Mana Pylons one block away from the Enchanting table and the level went up to 30.
<img width="792" alt="screen shot 2015-10-06 at 16 37 58" src="https://cloud.githubusercontent.com/assets/5294529/10313654/aaebd188-6c48-11e5-80de-39a2f30d2b63.png">
<img width="350" alt="screen shot 2015-10-06 at 16 37 53" src="https://cloud.githubusercontent.com/assets/5294529/10313656/ac1acb72-6c48-11e5-8dd2-ed3e2f2f9255.png">

So you either did the setup wrong or you have another mod that is somehow breaking it

**Comment by yrsegal** [comment] 2015-10-06 15:43
Huh. The pylons were right next to the table, though, which works without
EF.

**Comment by buttilda** [comment] 2015-10-06 15:49
I guess that's changed in 1.8 then.
As far as I remember the bookshelves always had to be one block away from the table XD

Closing since this is not a bug.

**Closed as completed by buttilda** 2015-10-06 15:49 UTC

**Comment by yrsegal** [comment] 2015-10-06 21:03
it works in 1.7, though...

**Comment by buttilda** [comment] 2015-10-06 22:05
http://minecraft.gamepedia.com/Enchantment_mechanics

**Comment by yrsegal** [comment] 2015-10-07 02:11
The pylons worked in 1.7, though, not sure if they have a special case
