### ISSUE TITLE
Anvil inaccessible

### ISSUE THREAD

**Issue by labpaw** [ganymedes01/Et-Futurum#29] opened 2015-09-06 15:19 UTC
I don't know what causing this. Maybe some mod conflicts with 1.8 anvil changes but I can't find it. Sometimes GUI pop ups for 1 second and immediately closes. No crashes happens.
Using Et Futurum 1.4.2, Forge 1492 and a lot of other mods.
List of mods: http://i.imgur.com/rey6FE7.jpg
I've uploaded modpack to [dropbox](https://www.dropbox.com/s/chkx5bep8n4jn47/fortesting.zip?dl=0)

**Comment by buttilda** [comment] 2015-09-06 15:25
Are you playing on a server?

**Comment by labpaw** [comment] 2015-09-06 15:38
No, singleplayer world.

**Comment by labpaw** [comment] 2015-09-09 09:54
Maybe you can add some debug feature (only for testing) which can detect if any other mod tries to change anvil? Then I can launch my modpack with this feature and send you a log?

**Comment by buttilda** [comment] 2015-09-09 13:33
I don't think that will be necessary.
I'll download your modpack and try it out myself and see if I can identify the problem.

**Comment by buttilda** [comment] 2015-09-09 13:33
Let me see if I got it right.

It doesn't happen 100% of the time, correct?

**Comment by labpaw** [comment] 2015-09-09 13:36
I can say that this happens 100% of the time. But sometimes you just able to see GUI for less of one second.

**Comment by buttilda** [comment] 2015-09-09 13:56
```
[14:55:34] [Server thread/WARN] [cuchaz.ships]: SERVER Unable to reflect on container class: ganymedes01.etfuturum.inventory.ContainerAnvil
java.lang.NullPointerException
    at cuchaz.ships.core.ShipIntermediary.getEntityDistanceSq(ShipIntermediary.java:65) [shipsMod-v1.7.10-1.0.3.jar:?]
```

This is the culprit

**Comment by buttilda** [comment] 2015-09-09 13:56
shipsMod-v1.7.10-1.0.3.jar
Seems to try to reflect on the class and upon failing it closes the GUI.

**Comment by labpaw** [comment] 2015-09-09 14:02
Thanks for looking into! So, should I ping cuchaz or it can be workarounded on your side?

**Comment by buttilda** [comment] 2015-09-09 15:07
You'll have to ping him. He's forcibly closing the GUI, nothing I can do to remedy it unfortunately )=

**Comment by labpaw** [comment] 2015-09-09 15:13
Alright pinging @cuchaz. I've also tried updated ships mod 1.0.4 and nothing changed.

**Comment by buttilda** [comment] 2015-09-09 15:21
Check if the mod has any config options you could turn off that might prevent the crash :)

**Comment by buttilda** [comment] 2015-09-15 21:21
Closing this since the guy never showed up.
If he ever replies and it turns out it's my fault (which I doubt) I'll re-open it.

**Comment by cuchaz** [comment] 2015-09-15 21:57
This problem probably isn't caused by the exception. It's just caught and logged without incident. Here's the relevant source code:

https://bitbucket.org/cuchaz/ships/src/d3af625fb1b958e1b6cba511ff93430393685365/src/cuchaz/ships/core/ShipIntermediary.java?at=1.7.10&fileviewer=file-view-default#ShipIntermediary.java-85

Ships Mod is trying to spoof distance checks from tile entities so they work correctly on ships. It's basically impossible to get the spoofing right for every possible tile entity since the information needed to do that correctly just isn't always available. Ships Mod makes a best guess and does what it can without leaving uncaught exceptions flying around. In this case, the best guess about distance to the player is probably much too large which causes Minecraft to close the gui. There's probably something I can do on my end to make the best guess better for unknown kinds of containers, but I can't get it working perfectly without the mod tile entity knowing it's on a ship. I'll eventually write the API for that, but even if I did, who would use it...

**Comment by buttilda** [comment] 2015-09-15 22:04
I see, well just to make sure, @Adaptivity could you remove ShipsMod and try it to access the anvil again?

From the explanation I don't see it being the cause of the problem, but before ruling it out completely it's better to be 100% sure :3

**Comment by cuchaz** [comment] 2015-09-15 22:06
Oh, Ships Mod is probably causing the problem. It gets all up in TileEnties and Containers using ASM. It changes the results of calls to methods that query player distance since TileEntities on ships are actually in a completely different coordinate system. The point of my comment before was just to say that's it's probably tricky to completely fix while keeping the TileEntity in the dark about what ships are.

**Comment by buttilda** [comment] 2015-09-15 23:33
oh right! Well shame it can't be fixed )=

Would it be possible to only execute the logic when the TileEntities are in the ship? Because then the anvils will still be accessible outside (which is a reasonable compromise I suppose)

**Comment by buttilda** [comment] 2015-09-15 23:37
Also, could it be because my container extends ContainerRepair? Or does it execute the same logic with any container?

**Comment by cuchaz** [comment] 2015-09-16 14:17
That's the trouble. Ships Mod can't tell if for certain if TileEntity is on a ship or not based only on its container and the distance request. Containers just don't have a lot of useful info in them, and the info that is there is not easily accessible, hence all the madness with reflection. The mod tries to guess by inspecting the container state, but that's pretty error-prone.

I think I know of a way to make the guessing smarter if I can just get the World instance the container thinks it's in. That might not be too hard to do with reflection.

Btw, there's an issue in my system to remind me to look into this:
https://bitbucket.org/cuchaz/ships/issues/224/guess-better-about-tileentity-entity

Also, extending ContainerRepair makes it more likely that Ships Mod can read your container correctly since it will act like a vanilla container.

**Comment by buttilda** [comment] 2015-11-09 14:35
Closing this since there's nothing I can do afaik

**Closed as completed by buttilda** 2015-11-09 14:35 UTC
